/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package LAB3;

import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.Random;
import javax.imageio.ImageIO;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JSlider;
import javax.swing.plaf.basic.BasicSliderUI;

/**
 *
 * @author DELL
 */
public class RacingBoy extends javax.swing.JFrame {

    Random random = new Random();

    public RacingBoy() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        batdau();
//        btn1.addKeyListener(new KeyAdapter() {
//            @Override
//            public void keyPressed(KeyEvent e) {
//                if (e.getKeyChar() == 1) {
//                    if (txtdungluong.getText().trim().equals("")) {
//                        JOptionPane.showMessageDialog(null, "Nhập dung lượng để chơi trò chơi !");
//                        txtdungluong.requestFocus();
//                        return;
//                    }
//                    init();
//                    startGame(js1);
//                    btn1.doClick();
//                }
//            }
//        });
    }

    private void batdau() {
        js1.setValue(0);
        js2.setValue(0);
        js3.setValue(0);
        js1.setUI(new mySliderUI(js1));
        js2.setUI(new mySliderUI(js2));
        js3.setUI(new mySliderUI(js3));
        btn1.setMnemonic('c');
        btn2.setMnemonic('v');
        btn3.setMnemonic('b');
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                int result = JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn thoát trò chơi", "Thoát", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (result == JOptionPane.YES_OPTION) {
                    System.exit(0);
                }

            }
        });
    }

    public void init() {
        js1.setMaximum(Integer.parseInt(txtdungluong.getText()));
        js1.setMinimum(0);
        js2.setMaximum(Integer.parseInt(txtdungluong.getText()));
        js2.setMinimum(0);
        js3.setMaximum(Integer.parseInt(txtdungluong.getText()));
        js3.setMinimum(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtdungluong = new javax.swing.JTextField();
        nc1 = new javax.swing.JLabel();
        nc2 = new javax.swing.JLabel();
        nc3 = new javax.swing.JLabel();
        js1 = new javax.swing.JSlider();
        js2 = new javax.swing.JSlider();
        js3 = new javax.swing.JSlider();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        txtplay1 = new javax.swing.JTextField();
        txtplay3 = new javax.swing.JTextField();
        txtplay2 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        k1 = new javax.swing.JLabel();
        k2 = new javax.swing.JLabel();
        k3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Nhập dung lượng (MB): ");

        txtdungluong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        nc1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nc1.setText("Người chơi 1: ");

        nc2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nc2.setText("Người chơi 2: ");

        nc3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nc3.setText("Người chơi 3: ");

        btn1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn1.setText("Người chơi 1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn2.setText("Người chơi 2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn3.setText("Người chơi 3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn4.setText("Chơi cùng lúc");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        txtplay1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtplay3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtplay2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton5.setText("Bắt Đầu");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Cách điều khiển: ");

        k1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        k1.setText("Người chơi 1 : c");

        k2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        k2.setText("Người chơi 2 : v");

        k3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        k3.setText("Người chơi 3 : b");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nc3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(js3, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtplay1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtplay2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtplay3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn4, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nc2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(js2, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nc1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(js1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                .addComponent(k3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtdungluong, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(k1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(k2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtdungluong, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(k1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(k2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(js1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(k3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(nc1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nc2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(js2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(nc3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(js3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtplay1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtplay2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtplay3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        if (txtdungluong.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Nhập dung lượng để chơi trò chơi !");
            txtdungluong.requestFocus();
            return;
        }
        if (txtplay1.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên người chơi  1 !");
            txtplay1.requestFocus();
            return;
        }
        if (txtplay2.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên người chơi  2 !");
            txtplay2.requestFocus();
            return;
        }
        if (txtplay3.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên người chơi  2 !");
            txtplay3.requestFocus();
            return;
        }
        init();
        startGame(js1);
        startGame(js2);
        startGame(js3);
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        if (txtdungluong.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Nhập dung lượng để chơi trò chơi !");
            txtdungluong.requestFocus();
            return;
        }
        if (txtplay1.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên người chơi  1 !");
            txtplay1.requestFocus();
            return;
        }
        if (txtplay2.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên người chơi  2 !");
            txtplay2.requestFocus();
            return;
        }
        if (txtplay3.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên người chơi  2 !");
            txtplay3.requestFocus();
            return;
        }
        init();
        startGame(js3);
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        if (txtdungluong.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Nhập dung lượng để chơi trò chơi !");
            txtdungluong.requestFocus();
            return;
        }
        if (txtplay1.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên người chơi  1 !");
            txtplay1.requestFocus();
            return;
        }
        if (txtplay2.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên người chơi  2 !");
            txtplay2.requestFocus();
            return;
        }
        if (txtplay3.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên người chơi  2 !");
            txtplay3.requestFocus();
            return;
        }
        init();
        startGame(js2);
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        if (txtdungluong.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Nhập dung lượng để chơi trò chơi !");
            txtdungluong.requestFocus();
            return;
        }
        if (txtplay1.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên người chơi  1 !");
            txtplay1.requestFocus();
            return;
        }
        if (txtplay2.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên người chơi  2 !");
            txtplay2.requestFocus();
            return;
        }
        if (txtplay3.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên người chơi  2 !");
            txtplay3.requestFocus();
            return;
        }
        init();
        startGame(js1);
    }//GEN-LAST:event_btn1ActionPerformed


    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if (txtdungluong.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Nhập dung lượng để chơi trò chơi !");
            txtdungluong.requestFocus();
            return;
        }
        if (txtplay1.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên người chơi  1 !");
            txtplay1.requestFocus();
            return;
        }
        if (txtplay2.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên người chơi  2 !");
            txtplay2.requestFocus();
            return;
        }
        if (txtplay3.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên người chơi  2 !");
            txtplay3.requestFocus();
            return;
        }

        nc1.setText(txtplay1.getText());
        nc2.setText(txtplay2.getText());
        nc3.setText(txtplay3.getText());
        btn1.setText(nc1.getText());
        btn2.setText(nc2.getText());
        btn3.setText(nc3.getText());
        k1.setText(nc1.getText()+" : c ");
        k2.setText(nc2.getText()+" : v ");
        k3.setText(nc3.getText()+" : b ");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RacingBoy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RacingBoy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RacingBoy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RacingBoy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RacingBoy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSlider js1;
    private javax.swing.JSlider js2;
    private javax.swing.JSlider js3;
    private javax.swing.JLabel k1;
    private javax.swing.JLabel k2;
    private javax.swing.JLabel k3;
    private javax.swing.JLabel nc1;
    private javax.swing.JLabel nc2;
    private javax.swing.JLabel nc3;
    private javax.swing.JTextField txtdungluong;
    private javax.swing.JTextField txtplay1;
    private javax.swing.JTextField txtplay2;
    private javax.swing.JTextField txtplay3;
    // End of variables declaration//GEN-END:variables

    private void startGame(JSlider slider) {
        // Tạo và khởi động một luồng mới
        Thread thread = new Thread(new Runnable() {
            @Override
            public void run() {
                runGame(slider);
            }
        });
        thread.start();

    }

    private void runGame(JSlider slider) {
        double mb = Double.parseDouble(txtdungluong.getText());
        while (slider.getValue() <= mb) {
            // Tăng giá trị của JSlider một cách ngẫu nhiên
            int value = slider.getValue() + random.nextInt(10) + 1;
            slider.setValue(value);
            // Đợi một khoảng thời gian ngắn
            try {
                Thread.sleep(500);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
            if (js1.getValue() == mb || js1.getValue() > mb) {
                JOptionPane.showMessageDialog(this, nc1.getText() + " Win");
                return;
            }
            if (js2.getValue() == mb || js2.getValue() > mb) {
                JOptionPane.showMessageDialog(this, nc2.getText() + " Win");
                return;
            }
            if (js3.getValue() == mb || js3.getValue() > mb) {
                JOptionPane.showMessageDialog(this, nc3.getText() + " Win");
                return;
            }
        }

    }

    private class mySliderUI extends BasicSliderUI {

        Image knobImage;

        public mySliderUI(JSlider aSlider) {

            super(aSlider);

            try {
                this.knobImage = ImageIO.read(new File("D:\\Car-icon.png"));

            } catch (IOException e) {

                e.printStackTrace();
            }
        }

        public void paintThumb(Graphics g) {

            g.drawImage(this.knobImage, thumbRect.x, thumbRect.y, 50, 35, null);

        }

    }

}
